# Generated by Django 4.2.21 on 2025-05-29 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='date',
        ),
        migrations.AddField(
            model_name='signup',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
