# Generated by Django 4.2.21 on 2025-05-29 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_signup_date_signup_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
