# Generated by Django 4.2.21 on 2025-06-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('poster', models.ImageField(upload_to='movies/')),
                ('rate', models.DecimalField(decimal_places=1, max_digits=3)),
                ('cast', models.TextField()),
                ('release_date', models.DateField()),
            ],
        ),
    ]
