# Generated by Django 4.2.21 on 2025-06-04 09:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_initial'),
        ('movie', '0003_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movie.seat')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.theater')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.signup')),
            ],
        ),
    ]
