# Generated by Django 4.2.21 on 2025-06-04 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
