# Generated by Django 4.2.21 on 2025-06-04 13:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_initial'),
        ('movie', '0007_remove_seat_theater_delete_booking_delete_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('seat_number', models.CharField(max_length=10)),
                ('is_booked', models.BooleanField(default=False)),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movie.theater')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('seats', models.ManyToManyField(to='movie.seat')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.theater')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.signup')),
            ],
        ),
    ]
