# Generated by Django 4.2.21 on 2025-06-08 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_seat_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='theater',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
