# Generated by Django 4.2.21 on 2025-06-28 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='theater',
        ),
        migrations.RemoveField(
            model_name='theater',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='Theater',
        ),
    ]
