# Generated by Django 4.2.21 on 2025-06-28 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='theater',
        ),
        migrations.RemoveField(
            model_name='theater',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='Theater',
        ),
    ]
